if(NOT DEFINED FRFXLL_BUILD OR "${FRFXLL_BUILD}" STREQUAL "")
  execute_process( COMMAND git rev-list --all	COMMAND wc -l OUTPUT_VARIABLE gitOut ERROR_VARIABLE gitErr)
  if("${gitErr}" STREQUAL "")
    STRING(REGEX REPLACE "(\r?\n)+$" "" "gitOut" "${gitOut}")
    if("${gitOut}" STREQUAL "")
      set(FRFXLL_BUILD "0")
      message("Warning: use default build number of ${FRFXLL_BUILD}")
    else()
      set(FRFXLL_BUILD "${gitOut}")
    endif()
  else()
    set(FRFXLL_BUILD "0")
  endif()
endif()
add_definitions( "-DFRFXLL_BUILD=${FRFXLL_BUILD}" )
